[tool.poe.tasks]
test = "pytest"
lint = "ruff check ."
snow-validate = "snow snowpark build"
snow-deploy-dev = "python _deploy.py"
snow-run-dev = "snow snowpark execute procedure DEMO_DB.DEMO_SCHEMA.SNOWFLAKE_AGENT_JOB()"
